# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
#
jdk:
  - openjdk13

services:

- postgresql

before_install:
- psql -c 'create database tracker;' -U postgres

cache:
 directories:
 - $HOME/.m2

# используем режим обычного пользователя для сборки проекта.
sudo: false
env:
  global:
    - CODECOV_TOKEN="77cbeb07-659c-4735-8063-8231e26ed482"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - tel.89194491005@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

